name: Building and Deploying Image to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
            docker login -u $username -p $password 

      - name: Build and Push Docker Image using Makefile
        run: |
          make docker
          make push

      - name: Log Docker Images for Verification
        run: make images
